#!/usr/bin/env python3
"""Recover Henrik Harmsen's extended display codes for creatures and objects.

Standard Umoria draws whole categories of creature with one letter: every
centipede is a 'c', every snake a 'J'. Henrik gave 96 creatures and 139
objects their own graphics by replacing the ASCII symbol in the data tables
with a code above the printable range -- "Filthy Street Urchin" is 133, not
't'; "Ancient Red Dragon" is 238, not 'D'. GFX_CORR then maps those codes to
individual tiles.

Modern Umoria has no such codes, and they cannot simply be written back into
`creatures_list[].sprite`, because gameplay reads that field: monsters are
bred by comparing it to 'd' and 'D', and the genocide command asks the player
for a symbol. So this extracts the mapping keyed by *name*, and the frontend
substitutes at drawing time.

Names are matched against modern Umoria's own tables, exactly where possible,
then ignoring case and punctuation, and finally through a small table of
renames recorded below. Anything still unmatched is reported rather than
dropped.

Usage:
    gen_amiga_codes.py --historical DIR --umoria DIR --hpp OUT.hpp
"""

import argparse
import re
import sys

ENTRY = re.compile(r'\{\s*"([^"]+)"\s*,((?:[^{}]|\{[^{}]*\})*?)\},', re.S)

# Field index of the display code within an entry, after brace groups are
# collapsed. Creatures: name, cmove, spells, cdefense, mexp, sleep, aaf, ac,
# speed, cchar. Objects: name, flags, tval, tchar.
CREATURE_CODE_FIELD = 8
OBJECT_CODE_FIELD = 2

# Objects Umoria renamed between 5.4 and 5.7.15. Without these five, the
# graphics Henrik drew for them would silently fall back to the plain symbol.
RENAMES = {
    "& Mace (Lead-filled)": "& Lead-Filled Mace",
    "[Beginners-Magik]": "[Beginners-Magick]",
    "[Magik I]": "[Magick I]",
    "[Magik II]": "[Magick II]",
    "[Exorcism and Dispelling]": "[Exorcisms and Dispellings]",
}


class ExtractError(Exception):
    pass


def normalise(name):
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def read_codes(path, code_field):
    """name -> display code, for entries whose symbol is a number."""
    with open(path, "r", errors="replace") as fh:
        source = fh.read()

    codes = {}
    total = 0
    for match in ENTRY.finditer(source):
        fields = [f.strip() for f in
                  re.sub(r"\{[^{}]*\}", "X", match.group(2)).split(",")]
        if len(fields) <= code_field:
            continue
        total += 1
        value = fields[code_field]
        if value.isdigit():
            codes.setdefault(match.group(1), int(value))
    if total == 0:
        raise ExtractError("no entries found in %s" % path)
    return codes


def read_names(path):
    with open(path, "r", errors="replace") as fh:
        return re.findall(r'\{\s*"([^"]+)"', fh.read())


def match_names(codes, names, label):
    """Map each historical name onto the modern one that still carries it."""
    exact = set(names)
    by_shape = {}
    for name in names:
        by_shape.setdefault(normalise(name), name)

    matched = {}
    unmatched = []
    for name, code in sorted(codes.items()):
        if name in exact:
            matched[name] = code
        elif name in RENAMES and RENAMES[name] in exact:
            matched[RENAMES[name]] = code
        elif normalise(name) in by_shape:
            matched[by_shape[normalise(name)]] = code
        else:
            unmatched.append(name)

    if unmatched:
        raise ExtractError(
            "%d %s could not be matched against modern Umoria: %s\n"
            "Their graphics would silently fall back to the plain symbol. Add "
            "the rename to RENAMES in this script." % (len(unmatched), label,
                                                       unmatched))
    return matched


def escape(name):
    return name.replace("\\", "\\\\").replace('"', '\\"')


def render_hpp(creatures, objects, gfx_corr_codes):
    def rows(mapping):
        return "\n".join('    {"%s", %d},' % (escape(name), code)
                         for name, code in sorted(mapping.items()))

    unmapped = sorted({c for c in list(creatures.values()) + list(objects.values())
                       if c not in gfx_corr_codes})
    note = ""
    if unmapped:
        note = ("//\n// WARNING: these codes have no explicit GFX_CORR entry, so they will\n"
                "// draw whatever the hallucination seeding put there: %s\n" % unmapped)

    return """// Generated by tools/gen_amiga_codes.py -- do not edit.
//
// Henrik Harmsen's extended display codes, recovered from the Amiga Moria
// Graphics 1.1 data tables and keyed by the names modern Umoria still uses.
// %d creatures and %d objects that standard Umoria draws with a shared letter
// had their own graphics.
%s#pragma once

#include <cstdint>

namespace moria::gfx {

struct NamedCode {
    const char *name;
    std::uint8_t code;
};

inline constexpr NamedCode kCreatureCodes[] = {
%s
};
constexpr int kCreatureCodeCount = %d;

inline constexpr NamedCode kObjectCodes[] = {
%s
};
constexpr int kObjectCodeCount = %d;

}  // namespace moria::gfx
""" % (len(creatures), len(objects), note, rows(creatures), len(creatures),
       rows(objects), len(objects))


def read_gfx_corr_codes(path):
    """The display codes GFX_CORR assigns explicitly, to check against."""
    sys.path.insert(0, __file__.rsplit("/", 1)[0])
    import gen_gfx_corr  # noqa: E402
    with open(path, "r", errors="replace") as fh:
        return set(gen_gfx_corr.parse(fh.read())["tiles"])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--historical", required=True,
                    help="the Amiga Moria Graphics 1.1 source directory")
    ap.add_argument("--umoria", required=True, help="modern Umoria's src directory")
    ap.add_argument("--hpp", help="write the generated header here")
    ap.add_argument("--expect-creatures", type=int, metavar="N")
    ap.add_argument("--expect-objects", type=int, metavar="N")
    args = ap.parse_args(argv)

    try:
        creature_codes = read_codes("%s/monsters.c" % args.historical,
                                    CREATURE_CODE_FIELD)
        object_codes = read_codes("%s/treasure.c" % args.historical,
                                  OBJECT_CODE_FIELD)
        creatures = match_names(creature_codes,
                                read_names("%s/data_creatures.cpp" % args.umoria),
                                "creatures")
        objects = match_names(object_codes,
                              read_names("%s/data_treasure.cpp" % args.umoria),
                              "objects")
        gfx_corr = read_gfx_corr_codes("%s/amiga_corrlist.c" % args.historical)
    except (ExtractError, OSError) as err:
        sys.stderr.write("%s\n" % err)
        return 1

    problems = []
    if args.expect_creatures is not None and len(creatures) != args.expect_creatures:
        problems.append("expected %d creatures with custom codes, found %d"
                        % (args.expect_creatures, len(creatures)))
    if args.expect_objects is not None and len(objects) != args.expect_objects:
        problems.append("expected %d objects with custom codes, found %d"
                        % (args.expect_objects, len(objects)))

    missing = sorted({c for c in list(creatures.values()) + list(objects.values())
                      if c not in gfx_corr})
    if missing:
        problems.append("display codes with no explicit GFX_CORR tile: %s" % missing)

    if problems:
        for problem in problems:
            sys.stderr.write("  - %s\n" % problem)
        return 1

    print("recovered %d creature codes and %d object codes; every one has a "
          "GFX_CORR tile" % (len(creatures), len(objects)))

    if args.hpp:
        with open(args.hpp, "w") as fh:
            fh.write(render_hpp(creatures, objects, gfx_corr))
    return 0


if __name__ == "__main__":
    sys.exit(main())
