#!/usr/bin/env python3
"""Extract Henrik Harmsen's GFX_CORR table from amiga_corrlist.c.

The table maps a Moria display code (0-255) to a position in the 8x8 tile
atlas. It is the single most valuable piece of the historical frontend and is
transcribed here mechanically rather than by hand, so the port cannot quietly
drift from the original.

Two things come out of the source file:

  * the explicit assignments -- 231 display codes in Amiga Moria Graphics 1.1;
  * the deliberate randomised seeding of all 256 entries that runs first, so
    that hallucination keeps showing graphics instead of falling back to
    ASCII. Only the parameters are extracted; the runtime reproduces the
    behaviour.

Usage:
    gen_gfx_corr.py amiga_corrlist.c --hpp amiga_tiles_table.generated.hpp
    gen_gfx_corr.py amiga_corrlist.c --check
"""

import argparse
import re
import sys

# GFX_CORR[x]['@'] = 10 ;   /  GFX_CORR[y][135] = 3;
ASSIGN = re.compile(
    r"GFX_CORR\s*\[\s*(?P<axis>[xy])\s*\]\s*\[\s*(?P<key>'(?:\\.|[^'])'|\d+)\s*\]"
    r"\s*=\s*(?P<value>-?\d+)\s*;")

# cx = randint(33)-1;  /  cy = randint(7)-1;
SEED = re.compile(r"(?P<var>c[xy])\s*=\s*randint\s*\(\s*(?P<range>\d+)\s*\)\s*-\s*1\s*;")

# if ((cx<20) && (cx>13)) cx -= 6;
SEED_FIXUP = re.compile(
    r"if\s*\(\s*\(\s*cx\s*<\s*(?P<hi>\d+)\s*\)\s*&&\s*\(\s*cx\s*>\s*(?P<lo>\d+)\s*\)\s*\)"
    r"\s*cx\s*-=\s*(?P<sub>\d+)\s*;")

C_ESCAPES = {
    "\\n": 10, "\\t": 9, "\\r": 13, "\\0": 0, "\\\\": 92, "\\'": 39,
    "\\\"": 34, "\\a": 7, "\\b": 8, "\\f": 12, "\\v": 11,
}


def parse_key(token):
    if token.isdigit():
        return int(token)
    body = token[1:-1]
    if body in C_ESCAPES:
        return C_ESCAPES[body]
    if len(body) == 1:
        return ord(body)
    raise ValueError("cannot interpret character literal %r" % token)


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def parse(text):
    text = strip_comments(text)

    xs, ys = {}, {}
    for m in ASSIGN.finditer(text):
        code = parse_key(m.group("key"))
        if not 0 <= code <= 255:
            raise ValueError("display code %d out of range" % code)
        (xs if m.group("axis") == "x" else ys)[code] = int(m.group("value"))

    seeds = {m.group("var"): int(m.group("range")) for m in SEED.finditer(text)}
    fixup = SEED_FIXUP.search(text)

    missing_pair = sorted(set(xs) ^ set(ys))
    if missing_pair:
        raise ValueError("display codes assigned on only one axis: %s" % missing_pair)

    return {
        "tiles": {c: (xs[c], ys[c]) for c in sorted(xs)},
        "seed_x_range": seeds.get("cx"),
        "seed_y_range": seeds.get("cy"),
        "seed_fixup": (int(fixup.group("lo")), int(fixup.group("hi")), int(fixup.group("sub")))
        if fixup else None,
    }


def render_hpp(table, source_name):
    tiles = table["tiles"]
    fixup = table["seed_fixup"]
    rows = "\n".join(
        "    {%3d, %2d, %2d},%s" % (code, x, y, _label(code))
        for code, (x, y) in tiles.items())

    if fixup:
        lo, hi, sub = fixup
        fixup_src = ("constexpr int kSeedFixupLow = %d;\n"
                     "constexpr int kSeedFixupHigh = %d;\n"
                     "constexpr int kSeedFixupSubtract = %d;\n" % (lo, hi, sub))
    else:
        fixup_src = ("constexpr int kSeedFixupLow = 0;\n"
                     "constexpr int kSeedFixupHigh = 0;\n"
                     "constexpr int kSeedFixupSubtract = 0;\n")

    return """// Generated by tools/gen_gfx_corr.py from %s -- do not edit.
//
// Henrik Harmsen's GFX_CORR table: Moria display code -> 8x8 tile atlas cell.
// %d display codes are assigned explicitly; the rest keep the randomised seed
// applied first by init_GFX_CORR(), which is what makes hallucination show
// graphics rather than ASCII.
#pragma once

#include <cstdint>

namespace moria::gfx {

struct TableEntry {
    std::uint8_t code;
    std::uint8_t x;
    std::uint8_t y;
};

// randint(N) in Moria returns 1..N, so the original seed covers 0..N-1.
constexpr int kSeedXRange = %s;
constexpr int kSeedYRange = %s;
%s
inline constexpr TableEntry kGfxCorr[] = {
%s
};

constexpr int kGfxCorrCount = %d;

}  // namespace moria::gfx
""" % (source_name, len(tiles), table["seed_x_range"], table["seed_y_range"],
       fixup_src, rows, len(tiles))


def _label(code):
    if 33 <= code <= 126:
        ch = chr(code)
        return "  // '%s'" % ("\\'" if ch == "'" else "\\\\" if ch == "\\" else ch)
    if code == 32:
        return "  // ' ' (space)"
    return ""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="path to amiga_corrlist.c")
    ap.add_argument("--hpp", help="write the generated header here")
    ap.add_argument("--check", action="store_true",
                    help="print a summary and verify known mappings")
    args = ap.parse_args(argv)

    with open(args.input, "r", errors="replace") as fh:
        table = parse(fh.read())

    tiles = table["tiles"]

    if args.check or not args.hpp:
        print("%s: %d display codes assigned" % (args.input, len(tiles)))
        print("seed: cx in 0..%d, cy in 0..%d, fixup %s"
              % (table["seed_x_range"] - 1, table["seed_y_range"] - 1, table["seed_fixup"]))
        extended = sorted(c for c in tiles if c > 127)
        print("extended codes >127: %d (%s..%s)"
              % (len(extended), extended[0] if extended else "-",
                 extended[-1] if extended else "-"))
        # Mappings quoted in the port brief; a mismatch means we misparsed.
        expected = {ord("@"): (10, 2), ord("."): (20, 1), ord("#"): (13, 2),
                    ord("B"): (2, 1), ord("D"): (2, 3), ord("!"): (12, 4),
                    ord("|"): (6, 6), ord("/"): (8, 6)}
        bad = {chr(c): (tiles.get(c), want) for c, want in expected.items()
               if tiles.get(c) != want}
        if bad:
            print("MISMATCH against the brief's documented mappings: %s" % bad)
            return 1
        print("all %d documented mappings match" % len(expected))

    if args.hpp:
        with open(args.hpp, "w") as fh:
            fh.write(render_hpp(table, args.input.rsplit("/", 1)[-1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
