#!/usr/bin/env python3
"""Convert a PSF1/PSF2 console font into an 8x8 C++ glyph table.

The Amiga original draws text with the ROM-resident Topaz font, which ships in
neither the 1.1 source archive nor the 1.2 binary distribution. Until real
Topaz glyph data is available this produces a metrically correct 8x8
stand-in, so the rest of the port can be built and looked at.

Only the metrics are load-bearing: 8x8 cells on an 8-pixel grid. Swapping in
Topaz later is a matter of regenerating this header.

Usage:
    gen_font.py /usr/share/consolefonts/Lat15-VGA8.psf.gz --hpp font8x8.generated.hpp
"""

import argparse
import gzip
import struct
import sys

PSF1_MAGIC = b"\x36\x04"
PSF1_MODE512 = 0x01
PSF2_MAGIC = b"\x72\xb5\x4a\x86"


def read_font(path):
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rb") as fh:
        data = fh.read()

    if data[:2] == PSF1_MAGIC:
        mode, charsize = data[2], data[3]
        count = 512 if mode & PSF1_MODE512 else 256
        glyphs = data[4:4 + count * charsize]
        return count, 8, charsize, glyphs

    if data[:4] == PSF2_MAGIC:
        (_ver, headersize, _flags, count, charsize,
         height, width) = struct.unpack("<IIIIIII", data[4:32])
        glyphs = data[headersize:headersize + count * charsize]
        return count, width, height, glyphs

    raise SystemExit("%s: not a PSF1 or PSF2 font" % path)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="PSF font file (optionally gzipped)")
    ap.add_argument("--hpp", required=True, help="header to write")
    args = ap.parse_args(argv)

    count, width, height, glyphs = read_font(args.input)
    if width != 8:
        raise SystemExit("%s is %dx%d; an 8-pixel wide font is required"
                         % (args.input, width, height))
    bytes_per_glyph = len(glyphs) // count

    rows = []
    for code in range(256):
        if code < count:
            g = glyphs[code * bytes_per_glyph:code * bytes_per_glyph + 8]
        else:
            g = b"\0" * 8
        g = (g + b"\0" * 8)[:8]
        rows.append("    {" + ", ".join("0x%02X" % b for b in g) + "},"
                    + ("  // '%s'" % chr(code) if 33 <= code <= 126 and chr(code) not in "\\'" else ""))

    header = """// Generated by tools/gen_font.py from %s -- do not edit.
//
// PLACEHOLDER. The Amiga original renders text with the ROM-resident Topaz
// font, which is not present in either historical archive. These glyphs have
// the right metrics (8x8 on an 8-pixel grid) but are not Topaz. Regenerate
// this header from real Topaz data to make the text pixel-authentic.
#pragma once

#include <cstdint>

namespace moria::ui {

// One byte per scanline, most significant bit leftmost.
inline constexpr std::uint8_t kFont8x8[256][8] = {
%s
};

}  // namespace moria::ui
""" % (args.input.rsplit("/", 1)[-1], "\n".join(rows))

    with open(args.hpp, "w") as fh:
        fh.write(header)
    print("%s: %d glyphs, %dx%d -> %s" % (args.input, count, width, height, args.hpp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
