#!/usr/bin/env python3
"""Convert a PSF1/PSF2 console font into an 8x8 C++ glyph table.

The Amiga original draws text with the ROM-resident Topaz font, which ships in
neither the 1.1 source archive nor the 1.2 binary distribution. Until real
Topaz glyph data is available this produces a metrically correct 8x8
stand-in, so the rest of the port can be built and looked at.

Only the metrics are load-bearing: 8x8 cells on an 8-pixel grid. Swapping in
Topaz later is a matter of regenerating this header.

A font that is not 8x8 is refused rather than cropped or padded, and a
truncated file is refused rather than being read with a miscomputed stride
that would misalign every glyph after the first.

Usage:
    gen_font.py /usr/share/consolefonts/Lat15-VGA8.psf.gz --hpp font8x8.generated.hpp
"""

import argparse
import gzip
import struct
import sys

PSF1_MAGIC = b"\x36\x04"
PSF1_MODE512 = 0x01
PSF1_HEADER_SIZE = 4
PSF2_MAGIC = b"\x72\xb5\x4a\x86"
PSF2_HEADER_SIZE = 32

CELL = 8


class FontError(Exception):
    pass


def read_font(path):
    """Return (glyph_count, width, height, stride, payload).

    `stride` is the declared bytes-per-glyph from the header, never inferred
    from how much data happened to be present.
    """
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rb") as fh:
        data = fh.read()

    if data[:2] == PSF1_MAGIC:
        if len(data) < PSF1_HEADER_SIZE:
            raise FontError("PSF1 header is truncated")
        mode, charsize = data[2], data[3]
        if charsize == 0:
            raise FontError("PSF1 header declares a zero character size")
        count = 512 if (mode & PSF1_MODE512) else 256
        # PSF1 is always 8 pixels wide, so one byte per scanline and the
        # declared character size is the height.
        width, height, stride = 8, charsize, charsize
        payload = data[PSF1_HEADER_SIZE:PSF1_HEADER_SIZE + count * stride]

    elif data[:4] == PSF2_MAGIC:
        if len(data) < PSF2_HEADER_SIZE:
            raise FontError("PSF2 header is truncated")
        (_ver, headersize, _flags, count, charsize,
         height, width) = struct.unpack("<IIIIIII", data[4:PSF2_HEADER_SIZE])
        if headersize < PSF2_HEADER_SIZE or headersize > len(data):
            raise FontError("PSF2 header size %d is out of range" % headersize)
        if charsize == 0 or count == 0:
            raise FontError("PSF2 header declares a zero glyph count or size")
        expected = height * ((width + 7) // 8)
        if charsize != expected:
            raise FontError(
                "PSF2 declares %d bytes per glyph but %dx%d needs %d"
                % (charsize, width, height, expected))
        stride = charsize
        payload = data[headersize:headersize + count * stride]

    else:
        raise FontError("not a PSF1 or PSF2 font")

    if len(payload) < count * stride:
        raise FontError(
            "glyph data is truncated: %d bytes present, %d needed for %d "
            "glyphs of %d bytes" % (len(payload), count * stride, count, stride))

    return count, width, height, stride, payload


def render_hpp(count, stride, payload, source_name):
    rows = []
    for code in range(256):
        if code < count:
            glyph = payload[code * stride:code * stride + CELL]
        else:
            glyph = b"\0" * CELL
        label = ""
        if 33 <= code <= 126 and chr(code) not in "\\'":
            label = "  // '%s'" % chr(code)
        rows.append("    {" + ", ".join("0x%02X" % b for b in glyph) + "}," + label)

    return """// Generated by tools/gen_font.py from %s -- do not edit.
//
// PLACEHOLDER. The Amiga original renders text with the ROM-resident Topaz
// font, which is not present in either historical archive. These glyphs have
// the right metrics (8x8 on an 8-pixel grid) but are not Topaz. Regenerate
// this header from real Topaz data to make the text pixel-authentic.
#pragma once

#include <cstdint>

namespace moria::ui {

// One byte per scanline, most significant bit leftmost.
inline constexpr std::uint8_t kFont8x8[256][8] = {
%s
};

}  // namespace moria::ui
""" % (source_name, "\n".join(rows))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="PSF font file (optionally gzipped)")
    ap.add_argument("--hpp", required=True, help="header to write")
    args = ap.parse_args(argv)

    try:
        count, width, height, stride, payload = read_font(args.input)
    except FontError as err:
        sys.stderr.write("%s: %s\n" % (args.input, err))
        return 1

    if width != CELL or height != CELL:
        sys.stderr.write(
            "%s is %dx%d; this port needs an %dx%d font. Cropping or padding "
            "one would silently change the text.\n"
            % (args.input, width, height, CELL, CELL))
        return 1

    with open(args.hpp, "w") as fh:
        fh.write(render_hpp(count, stride, payload, args.input.rsplit("/", 1)[-1]))
    print("%s: %d glyphs, %dx%d -> %s" % (args.input, count, width, height, args.hpp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
