// amiga-gfx-test -- the frontend on its own, with no game engine attached.
//
// This exists to answer one question before any Umoria code is touched: can
// we reproduce Henrik Harmsen's frontend accurately? Assets, SDL, the 640x200
// composition and the GFX_CORR mapping are all exercised here, so that when
// the engine is wired up only one thing is new at a time.
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "amiga_tiles.hpp"
#include "ui.hpp"

namespace {

using moria::ui::Color;

enum class Screen { Title, Tiles, Dungeon, Overview };

struct Args {
    Screen screen = Screen::Title;
    int scale = 2;
    bool fullscreen = false;
    bool headless = false;
    std::string screenshot;
};

const char *kUsage =
    "usage: amiga-gfx-test [--screen title|tiles|dungeon|overview]\n"
    "                      [--scale N] [--fullscreen] [--headless]\n"
    "                      [--screenshot FILE]\n"
    "\n"
    "  --screen      which screen to open on (default: title)\n"
    "  --scale       window is 640*N x 200*N (default: 2, so 1280x400)\n"
    "  --headless    render without a display, for screenshots and CI\n"
    "  --screenshot  write the 640x200 framebuffer to FILE (BMP) and exit\n";

bool parse_args(int argc, char **argv, Args *out) {
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        const bool has_value = (i + 1) < argc;
        if (arg == "--screen" && has_value) {
            const std::string value = argv[++i];
            if (value == "title") {
                out->screen = Screen::Title;
            } else if (value == "tiles") {
                out->screen = Screen::Tiles;
            } else if (value == "dungeon") {
                out->screen = Screen::Dungeon;
            } else if (value == "overview") {
                out->screen = Screen::Overview;
            } else {
                std::fprintf(stderr, "unknown screen '%s'\n", value.c_str());
                return false;
            }
        } else if (arg == "--scale" && has_value) {
            out->scale = std::atoi(argv[++i]);
        } else if (arg == "--screenshot" && has_value) {
            out->screenshot = argv[++i];
        } else if (arg == "--fullscreen") {
            out->fullscreen = true;
        } else if (arg == "--headless") {
            out->headless = true;
        } else if (arg == "--help" || arg == "-h") {
            std::fputs(kUsage, stdout);
            return false;
        } else {
            std::fprintf(stderr, "unknown option '%s'\n\n%s", arg.c_str(), kUsage);
            return false;
        }
    }
    return true;
}

// A stand-in dungeon level in display codes, laid out on the same 66x22 grid
// the Amiga used. Not generated by Moria -- just enough real tiles to check
// the geometry and the mapping.
class FakeLevel {
public:
    FakeLevel() : cells_(moria::ui::kMapCols * moria::ui::kMapRows, ' ') {
        room(2, 2, 30, 12);
        room(38, 4, 24, 14);
        corridor(32, 8, 38);

        put(10, 5, 'B');   // birds
        put(14, 7, 'D');   // dragon
        put(22, 9, 'p');   // human
        put(26, 4, 'k');   // kobold
        put(45, 7, '!');   // potion
        put(48, 11, '|');  // edged weapon
        put(52, 9, '/');   // polearm
        put(43, 14, '$');  // treasure
        put(56, 6, '*');   // gem
        put(20, 11, '+');  // door
        put(50, 15, '<');  // stairs up
        put(12, 10, '>');  // stairs down

        player_x_ = 8;
        player_y_ = 8;
    }

    void draw() const {
        for (int y = 0; y < moria::ui::kMapRows; ++y) {
            for (int x = 0; x < moria::ui::kMapCols; ++x) {
                const unsigned char code = at(x, y);
                if (code == ' ') {
                    continue;
                }
                moria::ui::tile(moria::ui::kMapColOffset + x,
                                moria::ui::kMapRowOffset + y, code);
            }
        }
        moria::ui::tile(moria::ui::kMapColOffset + player_x_,
                        moria::ui::kMapRowOffset + player_y_, '@');
    }

    void draw_overview() const {
        for (int y = 0; y < moria::ui::kMapRows; ++y) {
            for (int x = 0; x < moria::ui::kMapCols; ++x) {
                const unsigned char code = at(x, y);
                if (code == ' ') {
                    continue;
                }
                moria::ui::overview_tile(x, y, code);
            }
        }
        moria::ui::overview_tile(player_x_, player_y_, '@');
    }

    // Moria's original direction digits, laid out like the numeric keypad.
    void move(int digit) {
        static const int dx[10] = {0, -1, 0, 1, -1, 0, 1, -1, 0, 1};
        static const int dy[10] = {0, 1, 1, 1, 0, 0, 0, -1, -1, -1};
        if (digit < '1' || digit > '9') {
            return;
        }
        const int i = digit - '0';
        const int nx = player_x_ + dx[i];
        const int ny = player_y_ + dy[i];
        if (nx < 0 || ny < 0 || nx >= moria::ui::kMapCols || ny >= moria::ui::kMapRows) {
            return;
        }
        if (at(nx, ny) == '#' || at(nx, ny) == ' ') {
            return;
        }
        player_x_ = nx;
        player_y_ = ny;
    }

private:
    unsigned char at(int x, int y) const {
        return cells_[y * moria::ui::kMapCols + x];
    }

    void put(int x, int y, unsigned char code) {
        if (x >= 0 && y >= 0 && x < moria::ui::kMapCols && y < moria::ui::kMapRows) {
            cells_[y * moria::ui::kMapCols + x] = code;
        }
    }

    void room(int x, int y, int w, int h) {
        for (int j = 0; j < h; ++j) {
            for (int i = 0; i < w; ++i) {
                const bool edge = (i == 0 || j == 0 || i == w - 1 || j == h - 1);
                put(x + i, y + j, edge ? '#' : '.');
            }
        }
    }

    void corridor(int x0, int y, int x1) {
        for (int x = x0; x <= x1; ++x) {
            put(x, y, '.');
        }
    }

    std::vector<unsigned char> cells_;
    int player_x_ = 0;
    int player_y_ = 0;
};

void draw_sidebar() {
    // Columns 0..12 are the stat block on the Amiga; the dungeon starts at 13.
    moria::ui::text(0, 2, "Fenwick", Color::Normal);
    moria::ui::text(0, 4, "STR  18/40", Color::Normal);
    moria::ui::text(0, 5, "INT     11", Color::Normal);
    moria::ui::text(0, 6, "WIS     10", Color::StatLoss);
    moria::ui::text(0, 7, "DEX     16", Color::Normal);
    moria::ui::text(0, 8, "CON     17", Color::StatGain);
    moria::ui::text(0, 9, "CHR      9", Color::Normal);
    moria::ui::text(0, 11, "LEV      7", Color::Normal);
    moria::ui::text(0, 12, "EXP   1284", Color::Normal);
    moria::ui::text(0, 13, "AU     530", Color::Normal);
    moria::ui::text(0, 15, "MANA   0/0", Color::Normal);
    moria::ui::text(0, 16, "HP   41/52", Color::Warning);
    moria::ui::text(0, 18, "Hungry", Color::Warning);
    moria::ui::text(0, 23, "Lev 500ft", Color::Normal);
}

void draw_title() {
    moria::ui::show_title();
    moria::ui::text(24, 23, "Press SPACE to continue", Color::Normal);
}

// Every display code Henrik mapped by hand, with the code beside its tile.
void draw_tile_table() {
    moria::ui::text(0, 0, "GFX_CORR: every explicitly mapped display code",
                    Color::Normal);

    int col = 0;
    int row = 2;
    for (int code = 0; code < 256; ++code) {
        if (!moria::gfx::is_explicit(static_cast<std::uint8_t>(code))) {
            continue;
        }
        if (col + 5 > moria::ui::kCols) {
            col = 0;
            ++row;
        }
        if (row >= moria::ui::kRows) {
            break;
        }
        moria::ui::tile(col, row, static_cast<std::uint8_t>(code));

        char label[4];
        if (code > 32 && code < 127) {
            std::snprintf(label, sizeof(label), " %c ", static_cast<char>(code));
        } else {
            std::snprintf(label, sizeof(label), "%3d", code);
        }
        moria::ui::text(col + 1, row, label, Color::Normal);
        col += 5;
    }
}

void draw_dungeon(const FakeLevel &level) {
    moria::ui::text(0, 0, "You enter a dimly lit room.", Color::Normal);
    draw_sidebar();
    level.draw();
    moria::ui::text(13, 24, "numpad/arrows move   M overview   T tiles   ESC quit",
                    Color::Normal);
}

void draw_overview(const FakeLevel &level) {
    moria::ui::text(0, 0, "Reduced level map (1:4)", Color::Normal);
    level.draw_overview();
    moria::ui::text(13, 24, "any key returns", Color::Normal);
}

void render(Screen screen, const FakeLevel &level) {
    moria::ui::clear();
    switch (screen) {
        case Screen::Title: draw_title(); break;
        case Screen::Tiles: draw_tile_table(); break;
        case Screen::Dungeon: draw_dungeon(level); break;
        case Screen::Overview: draw_overview(level); break;
    }
    moria::ui::present();
}

// The game stays turn-based; the loop just hands control back between
// keypresses. A browser cannot be kept waiting inside a blocking read, and
// writing it this way means native and web run the same code rather than the
// web build getting a special case.
struct App {
    FakeLevel level;
    Screen screen = Screen::Title;
    bool running = true;
    bool dirty = true;
};

App g_app;

void handle_key(const moria::ui::KeyEvent &key) {
    if (key.key == moria::ui::kKeyQuit || key.key == moria::ui::kKeyEscape) {
        g_app.running = false;
        return;
    }
    switch (g_app.screen) {
        case Screen::Title:
            if (key.key == ' ') {
                g_app.screen = Screen::Dungeon;
            }
            break;
        case Screen::Overview:
        case Screen::Tiles:
            g_app.screen = Screen::Dungeon;
            break;
        case Screen::Dungeon:
            if (key.key == 'M' || key.key == 'm') {
                g_app.screen = Screen::Overview;
            } else if (key.key == 'T' || key.key == 't') {
                g_app.screen = Screen::Tiles;
            } else {
                g_app.level.move(key.key);
            }
            break;
    }
    g_app.dirty = true;
}

void tick() {
    for (;;) {
        const moria::ui::KeyEvent key = moria::ui::poll_key();
        if (key.key == moria::ui::kKeyNone) {
            break;
        }
        handle_key(key);
        if (!g_app.running) {
            return;
        }
    }

    if (g_app.dirty) {
        render(g_app.screen, g_app.level);
        g_app.dirty = false;
    } else {
        // Cheap, and it keeps the letterboxing right if the window resizes.
        moria::ui::present();
    }
}

}  // namespace

#ifdef __EMSCRIPTEN__
#include <emscripten.h>

namespace {
void emscripten_tick(void *) {
    tick();
    if (!g_app.running) {
        emscripten_cancel_main_loop();
        moria::ui::shutdown();
    }
}
}  // namespace
#endif

int main(int argc, char **argv) {
    Args args;
    if (!parse_args(argc, argv, &args)) {
        return 1;
    }

    moria::ui::Options options;
    options.scale = args.scale;
    options.fullscreen = args.fullscreen;
    options.headless = args.headless;
    options.title = "Moria Amiga -- graphics test";

    if (!moria::ui::init(options)) {
        std::fprintf(stderr, "could not open the display\n");
        return 1;
    }

    g_app.screen = args.screen;
    render(g_app.screen, g_app.level);
    g_app.dirty = false;

    if (!args.screenshot.empty()) {
        const bool ok = moria::ui::save_screenshot(args.screenshot.c_str());
        moria::ui::shutdown();
        if (ok) {
            std::printf("wrote %s\n", args.screenshot.c_str());
        }
        return ok ? 0 : 1;
    }

#ifdef __EMSCRIPTEN__
    // Hands control back to the browser between keypresses; never returns.
    emscripten_set_main_loop_arg(emscripten_tick, nullptr, 0, 1);
    return 0;
#else
    while (g_app.running) {
        tick();
        moria::ui::delay(8);
    }
    moria::ui::shutdown();
    return 0;
#endif
}
